/* bdcut00z.are: Imoen leaves the group in case she was in */

IF
	InPartyAllowDead("%IMOEN_DV_SOD%")
THEN
	RESPONSE #100
		CutSceneId(Player1)
		ActionOverride("Imoen_import_eq",TakeCreatureItems("%IMOEN_DV_SOD%",ALL))
		SmallWait(1)
		SetGlobal("BD_Imoen_Items","GLOBAL",1)
		ActionOverride("%IMOEN_DV_SOD%",LeaveParty())
		SmallWait(1)
		ActionOverride("%IMOEN_DV_SOD%",DestroySelf())
		SmallWait(1)
END

