/* imoen_bd4601_commenting.baf */
/* Comment in the Avernus Elevator */
IF
	Global("C#Imoen_bd_hellevator_ot","bd4601",0)  
	IfValidForPartyDialog("%IMOEN_DV_SOD%")  
	!GlobalTimerNotExpired("bd_hellevator_timer","bd4601")  
	!ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobal("C#Imoen_bd_hellevator_ot","bd4601",1)  // Avernus Elevator
		SetGlobalTimer("bd_hellevator_timer","bd4601",7)  
		DisplayStringHead("%IMOEN_DV_SOD%",@5535)  
END